FROM localhost/yellowtail AS nvidia-kmod

RUN --mount=type=tmpfs,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/lib/dnf \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=bind,dst=/tmp/build.sh,source=build/nvidia-kmod.sh \
    bash /tmp/build.sh

FROM localhost/yellowtail

COPY --from=nvidia-kmod /var/home/akmodsbuild /tmp/nvidia-kmod

RUN --mount=type=tmpfs,dst=/var/cache \
    --mount=type=tmpfs,dst=/var/lib/dnf \
    --mount=type=tmpfs,dst=/var/log \
    --mount=type=bind,dst=/tmp/build.sh,source=build/nvidia.sh \
    bash /tmp/build.sh

RUN bootc container lint
